'use client';
import {useEffect,useMemo,useState} from 'react';
const D={symbol:'009816',shares:0,averageCost:0,cash:250000,reserve:250000,goldTael:2.1,taiexHigh:0};
const money=v=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(v)||0);
const signed=v=>`${Number(v)>0?'+':''}${money(v)}`;
export default function Home(){
 const [s,setS]=useState(D),[m,setM]=useState(null),[g,setG]=useState(null),[gb,setGb]=useState(null),[shots,setShots]=useState([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState('正在更新資料…');
 useEffect(()=>{const a=localStorage.getItem('jay-v2-settings'),b=localStorage.getItem('jay-v2-snapshots'),c=localStorage.getItem('jay-v2-gold-base');if(a)setS({...D,...JSON.parse(a)});if(b)setShots(JSON.parse(b));if(c)setGb(JSON.parse(c))},[]);
 useEffect(()=>{if(!s.symbol)return;refresh();const t=setInterval(refresh,300000);return()=>clearInterval(t)},[s.symbol]);
 async function refresh(){setLoading(true);setMsg('正在更新股票、黃金與大盤…');const r=await Promise.allSettled([fetch('/api/market?symbol='+encodeURIComponent(s.symbol),{cache:'no-store'}).then(x=>x.json()),fetch('/api/gold',{cache:'no-store'}).then(x=>x.json())]);const mr=r[0].status==='fulfilled'?r[0].value:null,gr=r[1].status==='fulfilled'?r[1].value:null;if(mr?.ok){setM(mr);setS(c=>{const n={...c,taiexHigh:Math.max(Number(c.taiexHigh)||0,mr.taiex.price||0)};localStorage.setItem('jay-v2-settings',JSON.stringify(n));return n})}if(gr?.ok){setG(gr);goldBase(gr.taelBuy)}const e=[mr&&!mr.ok?mr.error:'',gr&&!gr.ok?gr.error:''].filter(Boolean);setMsg(e.length?'部分資料更新失敗：'+e.join('；'):'已更新：'+new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'}));setLoading(false)}
 function goldBase(p){const today=new Date().toISOString().slice(0,10),raw=localStorage.getItem('jay-v2-gold-base'),base=raw?JSON.parse(raw):null;let n;if(!base)n={date:today,price:p,previousPrice:p};else if(base.date!==today)n={date:today,price:p,previousPrice:base.price};else n={...base,price:p};localStorage.setItem('jay-v2-gold-base',JSON.stringify(n));setGb(n)}
 function set(k,v){const n={...s,[k]:v};setS(n);localStorage.setItem('jay-v2-settings',JSON.stringify(n))}
 const c=useMemo(()=>{const sp=m?.stock?.price||0,prev=m?.stock?.previousClose||0,sv=Number(s.shares)*sp,sd=Number(s.shares)*(sp-prev),st=Number(s.shares)*(sp-Number(s.averageCost)),gp=g?.taelBuy||0,gv=Number(s.goldTael)*gp,gprev=gb?.previousPrice||gp,gd=Number(s.goldTael)*(gp-gprev),total=Number(s.cash)+Number(s.reserve)+sv+gv,idx=m?.taiex?.price||0,high=Number(s.taiexHigh)||idx,dd=high>0?((idx/high)-1)*100:0;return{sp,sv,sd,st,gv,gd,total,dd}},[s,m,g,gb]);
 useEffect(()=>{if(!c.total)return;const d=new Date().toISOString().slice(0,10),n=[...shots.filter(x=>x.date!==d),{date:d,total:c.total}].slice(-90);setShots(n);localStorage.setItem('jay-v2-snapshots',JSON.stringify(n))},[c.total]);
 useEffect(()=>{const dd=c.dd;if(dd>-10||typeof Notification==='undefined')return;const tier=dd<=-30?'-30%':dd<=-20?'-20%':'-10%',key='jay-v2-notified-'+tier;if(localStorage.getItem(key))return;const go=()=>{const amount=tier==='-30%'?'15 萬':tier==='-20%'?'10 萬':'5 萬';new Notification('Jay Invest 加碼提醒',{body:`加權指數已觸及 ${tier}，依計畫提醒加碼 ${amount}。`});localStorage.setItem(key,'1')};if(Notification.permission==='granted')go();else if(Notification.permission==='default')Notification.requestPermission().then(x=>x==='granted'&&go())},[c.dd]);
 const a=c.dd<=-30?['第三次加碼提醒','NT$150,000','red']:c.dd<=-20?['第二次加碼提醒','NT$100,000','orange']:c.dd<=-10?['第一次加碼提醒','NT$50,000','green']:['照計畫定期定額','目前不用額外加碼','blue'];
 return <main><header className="topbar"><div><h1>Jay Invest</h1><p>自動市場追蹤</p></div><button className="refresh" onClick={refresh} disabled={loading}>{loading?'更新中':'更新'}</button></header>
 <section className="hero card"><span>總資產</span><strong>{money(c.total)}</strong><div className="daily">今日市場變化 <b className={c.sd+c.gd>=0?'up':'down'}>{signed(c.sd+c.gd)}</b></div><div className="goal"><i style={{width:`${Math.min(100,c.total/3000000*100)}%`}}/></div><small>300 萬目標：{(c.total/3000000*100).toFixed(1)}%</small></section>
 <section className="two"><article className="card metric"><span>股票今日損益</span><strong className={c.sd>=0?'up':'down'}>{signed(c.sd)}</strong><small>{m?.stock?.name||s.symbol}</small></article><article className="card metric"><span>黃金今日損益</span><strong className={c.gd>=0?'up':'down'}>{signed(c.gd)}</strong><small>持有 {s.goldTael} 兩</small></article></section>
 <section className={`card advice ${a[2]}`}><div><span>大盤距離追蹤高點</span><strong>{c.dd.toFixed(1)}%</strong></div><div className="adviceText"><b>{a[0]}</b><span>{a[1]}</span></div></section>
 <section className="card"><h2>資產明細</h2><Row l={`${s.symbol} 市值`} v={money(c.sv)}/><Row l="股票總損益" v={signed(c.st)} t={c.st}/><Row l="黃金市值" v={money(c.gv)}/><Row l="現金" v={money(s.cash)}/><Row l="預備金" v={money(s.reserve)}/></section>
 <section className="card"><h2>資產成長（近 90 天）</h2><Chart data={shots}/></section>
 <details className="card settings"><summary>設定持股與資產</summary><Field l="股票代號" v={s.symbol} f={v=>set('symbol',v.trim())}/><Field l="持有股數" type="number" v={s.shares} f={v=>set('shares',Number(v))}/><Field l="平均成本" type="number" step="0.01" v={s.averageCost} f={v=>set('averageCost',Number(v))}/><Field l="黃金持有（兩）" type="number" step="0.1" v={s.goldTael} f={v=>set('goldTael',Number(v))}/><Field l="現金" type="number" v={s.cash} f={v=>set('cash',Number(v))}/><Field l="預備金" type="number" v={s.reserve} f={v=>set('reserve',Number(v))}/><Field l="加權指數參考高點" type="number" v={s.taiexHigh} f={v=>set('taiexHigh',Number(v))}/><p className="hint">高點會在網站觀察到新高時自動上修；第一次使用可手動填入你採用的歷史高點。</p></details>
 <section className="card plan"><h2>009816 定期定額</h2><div>7 日　NT$4,000</div><div>14 日　NT$4,000</div><div>21 日　NT$4,000</div><div>28 日　NT$4,000</div><small>每月合計 NT$16,000，其餘保留現金。</small></section><footer>{msg}</footer></main>
}
function Row({l,v,t}){return <div className="row"><span>{l}</span><b className={t===undefined?'':t>=0?'up':'down'}>{v}</b></div>}
function Field({l,v,f,type='text',step}){return <label><span>{l}</span><input type={type} step={step} value={v} onChange={e=>f(e.target.value)}/></label>}
function Chart({data}){if(!data||data.length<2)return <div className="empty">開啟網站並累積兩天資料後，這裡會出現曲線。</div>;const vals=data.map(x=>x.total),min=Math.min(...vals),max=Math.max(...vals),pts=data.map((x,i)=>`${i/(data.length-1)*100},${92-(x.total-min)/Math.max(1,max-min)*84}`).join(' ');return <svg viewBox="0 0 100 100" preserveAspectRatio="none" className="chart"><polyline points={pts} fill="none" stroke="currentColor" strokeWidth="2.5"/></svg>}
